In [1]:
import numpy as np

In [2]:
f = np.arange(20).reshape(5, 4)

In [3]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
f.sum()

190

In [6]:
f.sum(axis=1)

array([ 6, 22, 38, 54, 70])

In [9]:
np.sum(f, axis=1)

array([ 6, 22, 38, 54, 70])

In [8]:
np.median(f, axis=0)

array([ 8.,  9., 10., 11.])

In [19]:
norm = np.random.randn(500, 400)

In [20]:
norm.mean()

-0.0007355607704445046

In [17]:
np.std(norm)

1.001542436630677

In [22]:
sum(f)

array([40, 45, 50, 55])

In [23]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [24]:
f + 5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [29]:
(np.random.rand(5, 5) * 100).astype(int)

array([[57, 90, 66, 16, 40],
       [50, 57, 13, 68, 12],
       [95, 94, 32, 69, 74],
       [52, 48, 76, 59, 19],
       [89, 12, 34, 82,  6]])

In [31]:
np.random.randint(0, 100, size=(5, 5))

array([[83, 64,  1,  1, 39],
       [36,  1, 95, 79, 82],
       [52, 91, 52,  8,  6],
       [ 3,  7, 41, 74,  3],
       [59, 54, 63, 39, 17]])

In [33]:
np.random.random(size=(4, 6))

array([[0.23405645, 0.54294826, 0.18642811, 0.53818077, 0.52579367,
        0.58599664],
       [0.20310576, 0.31440038, 0.67225443, 0.3420139 , 0.63184103,
        0.12535672],
       [0.67954964, 0.77995075, 0.37522093, 0.40360264, 0.38292136,
        0.20466839],
       [0.91558639, 0.80130234, 0.3374424 , 0.13485894, 0.46077782,
        0.034958  ]])

In [54]:
np.random.seed(6)

In [55]:
np.random.randint(0, 100, size=(5, 5))

array([[10, 73, 99, 84, 79],
       [80, 62, 25,  1, 75],
       [77, 57, 26, 33, 68],
       [33,  8,  2, 76, 84],
       [91, 31, 66,  5, 26]])

In [51]:
np.random.randint(0, 100, size=(5, 5))

array([[85, 41, 64,  6, 19],
       [ 2, 79, 30, 35, 26],
       [60, 66, 76, 96, 67],
       [ 2, 10, 51,  0, 93],
       [93, 94,  0, 11, 30]])

In [57]:
np.random.randn(5, 4)

array([[ 1.28205270e+00,  1.87948270e+00,  6.54300947e-01,
        -1.42547661e+00],
       [-3.00436306e-01, -1.56337455e+00,  2.07207723e+00,
         2.20192358e-03],
       [ 9.54913953e-01, -9.98243125e-01, -2.31331140e+00,
        -4.41243509e-01],
       [-2.19079928e-01,  7.51428243e-01, -1.06117427e-01,
         8.92561952e-01],
       [ 8.51940462e-01,  3.06554568e-01,  4.19285127e-01,
         1.35073657e-02]])

In [59]:
np.power(f, 2)

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [60]:
f ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [65]:
np.sum(f, axis=1, keepdims=True)

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [66]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [69]:
s = np.arange(8).reshape(4, 2)

In [70]:
s

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [71]:
np.dot(f, s)

array([[ 28,  34],
       [ 76,  98],
       [124, 162],
       [172, 226],
       [220, 290]])

In [72]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [74]:
t = np.arange(20).reshape(5, 4)

In [76]:
np.hstack([f, t])

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19]])

In [77]:
np.vstack([f, t])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [81]:
np.concatenate([f, t], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19]])