In [7]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_regression

In [20]:
class CustomLinearRegression:
        
    def fit(self, X, y):
        
        self.__mean = X.mean(axis=0)
        self.__std = X.std(axis=0)

        X = (X - self.__mean) / self.__std
        
        X_mod = np.hstack([np.ones((X.shape[0] ,1)), X])
        y_mod = y.reshape(-1, 1)
        
        first = np.linalg.inv(np.dot(X_mod.T, X_mod))
        second = np.dot(X_mod.T, y_mod)
        
        self.theta_ = np.dot(first, second)
        
    def hypo(self, X):
        return np.dot(X, self.theta_)
    
    def predict(self, X):
        X_mod = (X - self.__mean) / self.__std
        X_mod = np.hstack([np.ones((X_mod.shape[0] ,1)), X_mod])
        y_h = self.hypo(X_mod)
        return y_h.flatten()


In [21]:
from sklearn.datasets import load_boston

In [22]:
d = load_boston()

In [23]:
X, y = d.data, d.target

In [24]:
model = CustomLinearRegression()

In [25]:
model.fit(X, y)

In [26]:
model.theta_

array([[ 2.25328063e+01],
       [-9.20411128e-01],
       [ 1.08098058e+00],
       [ 1.42967124e-01],
       [ 6.82203460e-01],
       [-2.06009246e+00],
       [ 2.67064141e+00],
       [ 2.11206306e-02],
       [-3.10444805e+00],
       [ 2.65878654e+00],
       [-2.07589814e+00],
       [-2.06215593e+00],
       [ 8.56640436e-01],
       [-3.74867982e+00]])

In [27]:
model.predict(X[:10])

array([30.00821269, 25.0298606 , 30.5702317 , 28.60814055, 27.94288232,
       25.25940048, 23.00433994, 19.5347558 , 11.51696539, 18.91981483])

In [28]:
y[:10]

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9])

In [29]:
from sklearn.linear_model import LinearRegression

In [30]:
model = LinearRegression()

In [59]:
model.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [60]:
model.predict(X[:10])

array([30.00821269, 25.0298606 , 30.5702317 , 28.60814055, 27.94288232,
       25.25940048, 23.00433994, 19.5347558 , 11.51696539, 18.91981483])

In [8]:
print(d.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [97]:
LinearRegression?

Init signature: LinearRegression(fit_intercept=True, normalize=False, copy_X=True, n_jobs=1)
Docstring:     
Ordinary least squares Linear Regression.

Parameters
----------
fit_intercept : boolean, optional, default True
    whether to calculate the intercept for this model. If set
    to False, no intercept will be used in calculations
    (e.g. data is expected to be already centered).

normalize : boolean, optional, default False
    This parameter is ignored when ``fit_intercept`` is set to False.
    If True, the regressors X will be normalized before regression by
    subtracting the mean and dividing by the l2-norm.
    If you wish to standardize, please use
    :class:`sklearn.preprocessing.StandardScaler` before calling ``fit`` on
    an estimator with ``normalize=False``.

copy_X : boolean, optional, default True
    If True, X will be copied; else, it may be overwritten.

n_jobs : int, optional, default 1
    The number of jobs to use for the computation.
    If -1 all CPUs