In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_regression

In [20]:
bias = 100

X, y, coef = make_regression(n_features=4, coef=True, bias=bias)

In [21]:
X.shape

(100, 4)

In [22]:
coef

array([68.69343781, 31.89225619, 46.72831503, 68.12470077])

In [23]:
theta = np.concatenate([[bias], coef]).reshape(-1, 1)

In [24]:
theta

array([[100.        ],
       [ 68.69343781],
       [ 31.89225619],
       [ 46.72831503],
       [ 68.12470077]])

In [25]:
X_mod = np.hstack([np.ones((X.shape[0] ,1)), X])

In [26]:
X_mod.shape

(100, 5)

In [27]:
np.dot(X_mod, theta).flatten()[:20]

array([ 124.5739519 ,  183.27866218,  156.53973516,   48.61681689,
        114.80885658,   22.25325792,  179.51766322, -217.63578349,
          6.74573316,  -29.65629599, -124.17722606,   71.19940753,
        104.71992176,   37.67099379,  128.3608108 ,  191.05522934,
        277.10085788,  187.46403138,    2.38818087,  179.0586724 ])

In [28]:
y[:20]

array([ 124.5739519 ,  183.27866218,  156.53973516,   48.61681689,
        114.80885658,   22.25325792,  179.51766322, -217.63578349,
          6.74573316,  -29.65629599, -124.17722606,   71.19940753,
        104.71992176,   37.67099379,  128.3608108 ,  191.05522934,
        277.10085788,  187.46403138,    2.38818087,  179.0586724 ])