In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import OneHotEncoder

In [14]:
data = np.random.randint(0, 3, 10)

In [15]:
data

array([2, 0, 1, 1, 2, 0, 0, 0, 2, 0])

In [16]:
ohe = OneHotEncoder()

In [17]:
ohe.fit(data.reshape(-1, 1))

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [18]:
ohe.categories_

[array([0, 1, 2])]

In [19]:
ohe.transform(data.reshape(-1, 1)).todense()

matrix([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

In [20]:
colors = ["red", "green", "blue"]

In [23]:
out = np.array([colors[i] for i in data]).reshape(-1, 1)

In [24]:
out

array([['blue'],
       ['red'],
       ['green'],
       ['green'],
       ['blue'],
       ['red'],
       ['red'],
       ['red'],
       ['blue'],
       ['red']], dtype='<U5')

In [25]:
ohe.fit(out)

OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)

In [26]:
ohe.categories_

[array(['blue', 'green', 'red'], dtype='<U5')]

In [31]:
print(ohe.transform(out))

  (0, 0)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 1)	1.0
  (4, 0)	1.0
  (5, 2)	1.0
  (6, 2)	1.0
  (7, 2)	1.0
  (8, 0)	1.0
  (9, 2)	1.0


In [34]:
out = np.array([-10, 5, 10, 20, 30])

In [35]:
np.exp(out)

array([4.53999298e-05, 1.48413159e+02, 2.20264658e+04, 4.85165195e+08,
       1.06864746e+13])

In [36]:
np.exp(out) / np.sum(np.exp(out))

array([4.24816138e-18, 1.38873134e-11, 2.06106005e-09, 4.53978686e-05,
       9.99954600e-01])